import './reset.css';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import FocusOnHeading from '@/components/FocusOnHeading';
import StyledLink from '@/components/StyledLink';

const jost = Jost({
  subsets: ['latin'],
  variable: '--font-general',
  preload: true,
});

export const metadata: Metadata = {
  title: 'Designo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <StyledLink href="#main" id="skip-link" variant="dark" plainAnchor>
          Skip to Main Content
        </StyledLink>
        <FocusOnHeading />
        <Header />
        <main id="main">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
